immutable/unity-immutable-sdk

- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Environment.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Environment.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Private/Request.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
* Added 'environment' when initialising SDK
* Removed unused Android deeplink callback proxy
* Fixed connect PKCE error handling
> feat: environment

- sample/Assets/Scripts/UnauthenticatedScript.cs
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/Model/CreateTransferResponseV1.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/CreateTransferResponseV1.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/Token.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Token.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/UnsignedTransferRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/UnsignedTransferRequest.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportFunction.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Models.meta
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
This is the bridged transfer method exposed by the TS SDK.
> feat: implement ImxTransfer

- src/Packages/Passport/Runtime/Scripts/Private/Model/CreateBatchTransferResponse.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/CreateBatchTransferResponse.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/NftTransferDetails.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/NftTransferDetails.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/UnsignedTransferRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportFunction.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Been tested and works as expected.
> feat: add support to batch nft transfer

- README.md
Passport should now be attached to a development environment in the dev hub, this PR updates the readme to reflect those changes.
> [HUB-223]: Update register passport steps

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/CreateTransferResponseV1.cs
Also, fix transfer response json.
The transfer response has been updated in the TS SDK to be included at root level, which follows the standard created by older methods, making it more consistent and easier to parse. https://github.com/immutable/ts-immutable-sdk/pull/754
https://github.com/immutable/unity-immutable-sdk/assets/662062/9f5fa548-c3aa-46db-abb0-217edfc01113
> Include transfer in sample app

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
If more than the first column of inputs are filled in, the sample app uses batch transfer instead.
https://github.com/immutable/unity-immutable-sdk/assets/662062/64efb95a-0493-4386-9c2a-7fc382a7d218
> feat: implement bulk transfer

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Editor/PassportPostprocess.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/GetBalanceRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/GetBalanceRequest.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/RequestAccountsResponse.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/RequestAccountsResponse.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/TransactionRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/TransactionRequest.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportFunction.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Models.meta
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Passport package
* Added ZK EVM functions
* Connect EVM
* Request accounts `eth_requestAccounts`
* Get balance `eth_getBalance`
* Send transaction `eth_sendTransaction` added, but we cannot test it yet since invisible signing is not available
* Removed try-catch around ImxTransfer and ImxBatchTransfer functions, as the underlying browser communications manager will throw the error anyway.
Sample app
* Cleaned up sample app UI
* Added buttons for ZK EVM functions
* Set callback URI for mobile only
> feat: zkevm connect, request accounts, get balance and set up send transaction

- .github/workflows/test.yml
- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Helper/WebBrowserUtils.cs
* Set up GitHub Action to run unit tests
* Remove the need for UNIX support in UWB
* Added extra log message to sample app when passport fails to connect silently
> ci: run unit tests

- sample/Assets/Scripts/UnauthenticatedScript.cs
Removed unused `OnReady()` function in sample app
> chore: remove unused on ready method in sample app

- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/InitRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/VersionInfo.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/VersionInfo.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
[DX-2357](https://immutable.atlassian.net/browse/DX-2357)
Send engine version and platform info from Passport init to game bridge.
[DX-2357]: https://immutable.atlassian.net/browse/DX-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DX-2357] Send engine and platform info on Passport init

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/UnauthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Editor/PassportAndroidProcessor.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
* zkEVM send transaction request: only send non-null values
* Add zkEVM send transaction to sample app
* Allow users to enter account when getting zkEVM balance
> feat: zkevm send transaction

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
There was no guarantee the PKCE completion was going to be executed on the main thread, which causes issues specially when updating the UI after the code was completed.
> fix: pkce completion is done on the main thread

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
Some failures coming from the browser call were not being properly caught and bubbled up in form of a completion of the task, which would cause the UI to be permanently stuck in Connecting, even though it had actually failed.
> fix: PKCE flow would be stuck in certain failures

- src/Packages/Passport/Runtime/Scripts/Private/Json/JsonHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Response/CreateBatchTransferResponse.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Response/CreateTransferResponseV1.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
* Fix IMX batch transfer not working correctly because serialisation for arrays is broken
* Fix response models not deserialised properly
> [DX-2493] fix: imx batch transfer not serialising and deserialising correctly

- LICENSE
- README.md
> [DX-2523] docs: create license

- .github/pull_request_template.md
> [DX-2582] chore: create pull_request_template.md

- .github/pull_request_template.md
Added public documentation to PR template
N/A
> chore: add update docs requirement to pull_request_template.md

- .jscpd.json
Add JSCPD config file to exclude unit tests folder
> ci: create .jscpd.json

- sample/Assets/Scenes/AuthenticatedScene.unity
Fixed sample app "Is Register Offchain" button text to "Is Registered Offchain"
> fix: sample app is registered offchain button text

- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/Event/AnalyticsEvent.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/TrackData.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/VersionInfo.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Helpers/JsonHelpersTests.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
- Add tracking to auth functions
- Added device model to version information
- Removed unused imports and unnecessary logs
- Updated app name and macOS standalone app ID
N/A
- ~~[ ] Sample app is updated with new SDK changes~~
- ~~[ ] Updated public documentation with new SDK changes ([Immutable X](https://docs.immutable.com/docs/x/sdks/unity) and [Immutable zkEVM](https://docs.immutable.com/docs/zkEVM/sdks/unity))~~
- ~~[ ] Sample game is updated with new SDK changes~~
- ~~[ ] Replied to GitHub issues~~
> [DX-2647] chore: track auth functions

- sample/Packages/manifest.json
- sample/Packages/packages-lock.json
- sample/ProjectSettings/ProjectSettings.asset
Updated the sample app to use a stable version of the unit test framework instead of the experimental one.
N/A
> [DX-2768] test: update sample project unit test framework version

- src/Packages/Passport/package.json
Bump up version in `package.json`.
> build: bump up version

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Model/BrowserResponse.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportFunction.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
Added a function to retrieve the list of external wallets linked to a user's Passport account via the Dashboard.
Use `GetLinkedAddresses` to retrieve the list of external wallets linked to a user's Passport account via the Dashboard.
> [DX-2974] feat: get linked addresses

- sample/Assets/Scenes/UnauthenticatedScene.unity
- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
* Ability to set a timeout for Device Code Auth (`Login` and `ConnectImx`).
* Updated sample app so that user can specify the timeout when logging via Device Code Auth.
Added timeout settings for `Login` and `ConnectImx` functions.
> [DX-3001] feat: ability to set device code auth timeout

- sample/Assets/Editor/MacBuilder.cs
- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/SelectAuthMethod.unity
- sample/Assets/Scenes/SelectAuthMethod.unity.meta
- sample/Assets/Scripts/SampleAppManager.cs
- sample/Assets/Scripts/SelectAuthMethodScript.cs
- sample/Assets/Scripts/SelectAuthMethodScript.cs.meta
- sample/Assets/Scripts/UnauthenticatedScript.cs
- sample/ProjectSettings/EditorBuildSettings.asset
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Refactor sample app to have a dedicated scene for selecting auth method
> [DX-2996] refactor: sample app select auth method

- sample/Assets/Scenes/SelectAuthMethod.unity
- sample/Assets/Scenes/UnauthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/SampleAppManager.cs
- sample/Assets/Scripts/SelectAuthMethodScript.cs
- sample/Assets/Scripts/UnauthenticatedScript.cs
- sample/Packages/manifest.json
- sample/Packages/packages-lock.json
- sample/ProjectSettings/EditorBuildSettings.asset
- sample/ProjectSettings/PackageManagerSettings.asset
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Refactor sample app select auth method and unauthenticated scenes.
> [DX-3021] refactor: sample app select auth method and unauthenticated scenes

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/SelectAuthMethod.unity
- sample/Assets/Scenes/UnauthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/SafeArea.cs
- sample/Assets/Scripts/SafeArea.cs.meta
- sample/Assets/Scripts/SelectAuthMethodScript.cs
- sample/Assets/Scripts/UnauthenticatedScript.cs
- Refactored sample app authenticated scene passport functions to include more comments
- Adjusted sample app UI to fit within the safe area on mobile devices
- Updated the sample select auth screen to use buttons instead of toggles
> [DX-3025] refactor: authenticated scene passport fns

- sample/Assets/Editor/MacBuilder.cs
Added new scenes to sample app Mac Builder script
> [DX-2989] chore: update mac builder

- sample/Assets/Editor/WindowsBuilder.cs
- sample/Assets/Editor/WindowsBuilder.cs.meta
Script to build Windows sample app for AltTester.
> [DX-3070] chore: add windows builder script for alttester

- sample/Assets/Editor/MacBuilder.cs
Added another build script to build the sample app for Mac without AltTester.
> [DX-3098] chore: mac build script to build without alttester

- sample/Assets/Editor/WindowsBuilder.cs
Added another build script to build the sample app for Windows without AltTester.
> [DX-3100] chore: build script for windows sample app

- sample/Assets/Scenes/ZkEvmSendTransaction.unity
- sample/Assets/Scripts/ZkEvm/ZkEvmSendTransactionScript.cs
Add a toggle for getting transaction receipt to the send transaction scene of the sample app.
> [DX-3123] test: add get transaction receipt toggle to sample app send transaction scene

- sample/Assets/Editor/AndroidBuilder.cs
- sample/Assets/Editor/AndroidBuilder.cs.meta
Build scripts for Android sample app (with and without AltTester)
> [DX-3106] test: build android script

- .github/workflows/linter.yml
- sample/Assets/Scripts/SelectAuthMethodScript.cs
> [SDK-3322] pkce for webgl only

- .github/workflows/test-build.yml
- WebGL.md
Deploy WebGL build and host on github pages
> [SDK-334] deploy webgl

- .github/workflows/ui-tests.yml
Make sure only 1 job runs UI tests at a time so that the test doesn't conflict.
> [SDK-3400]: Make sure only 1 job runs UI tests at a time

- .github/workflows/ui-tests.yml
- sample/Tests/browserstack.yml
- sample/Tests/requirements.txt
- sample/Tests/test/test_android.py
> [DX-3421] android UI test on CI (BrowserStack)

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/SetCallTimeout.unity
- sample/Assets/Scenes/SetCallTimeout.unity.meta
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/Other.meta
- sample/Assets/Scripts/Other/SetCallTimeoutScript.cs
- sample/Assets/Scripts/Other/SetCallTimeoutScript.cs.meta
- sample/ProjectSettings/EditorBuildSettings.asset
- sample/Tests/src/fetch_otp.py
- sample/Tests/test/test.py
- sample/Tests/test/test_windows.py
- sample/Tests/test_windows.ps1
* Fix Windows UI tests
* Added set call timeout to sample app
> [DX-3445] test: fix windows ui test

- sample/Assets/Editor/MacBuilder.cs
- sample/Assets/Editor/MobileBuilder.cs
- sample/Assets/Editor/WindowsBuilder.cs
- sample/Assets/Scenes/SetCallTimeout.unity
- sample/Tests/src/fetch_otp.py
- sample/Tests/test/test.py
- sample/Tests/test_windows.ps1
- Updated test account
- Fixed build script missing SetCallTimeout scene
- Fixed SetCallTimeout scene cancel button listener
- Fixed Windows UI tests
> [DX-3449] test: new test account

- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/LinkWallet.unity
- sample/Assets/Scenes/LinkWallet.unity.meta
- sample/Assets/Scenes/SelectAuthMethod.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/Passport.meta
- sample/Assets/Scripts/Passport/LinkWalletScript.cs
- sample/Assets/Scripts/Passport/LinkWalletScript.cs.meta
- sample/ProjectSettings/EditorBuildSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/JsonHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Helpers/JsonHelpersTests.cs
- Included an example of using zkEVM API to link external wallets.
- Simplified JSON helpers method
> [DX-3476] feat: link wallet example using zkevm api package

- sample/Assets/Scenes/Other/LaunchBrowser.unity
- sample/Assets/Scripts/Other/LaunchBrowserScript.cs
- src/Packages/Passport/Runtime/Scripts/Public/Immutable.Passport.Runtime.asmdef
- Fixed assembly definition file
- I added an open dev tools button to the sample for the Windows launch browser scene.
> [DX-3465] fix: windows webview assembly file and sample app webview

- sample/Packages/manifest.json
- sample/Packages/packages-lock.json
- src/Packages/Marketplace/Runtime/OnRamp/OnRamp.cs
- Updated on-ramp link configuration.
- Added marketplace package to sample app.
> [DX-3502] feat: marketplace on ramp link configuration

- src/Packages/Marketplace/CHANGELOG.md.meta
- src/Packages/Marketplace/LICENSE.md.meta
- src/Packages/Marketplace/README.md.meta
- src/Packages/Marketplace/Runtime/OnRamp/OnRamp.cs
- src/Packages/Marketplace/Runtime/Swap.meta
- src/Packages/Marketplace/Runtime/Swap/Swap.cs
- src/Packages/Marketplace/Runtime/Swap/Swap.cs.meta
- Added function to generate the swap URL into the Marketplace package
- Added docs for Marketplace OnRamp class
- Customers can utilise the Marketplace package to generate the swap URL for use in their game.
> [DX-3524] feat: swap, marketplace docs

- src/Packages/Marketplace/Runtime/LinkFactory.cs
Fixed Marketplace package on-ramp link default values.
> [DX-3550] feat: marketplace on ramp default values

- sample/Tests/test/test_mac.py
- sample/Tests/test/test_windows_helpers.py
Fix UI test to handle device confirmation screen.
> [DX-3561] test: fix device code auth ui test

- src/Packages/Passport/Editor/PassportAndroidProcessor.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/ZkEvm/ZkEvmSendTransactionScript.cs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- .github/workflows/ui-tests.yml
- sample/build_ios.sh
- Ensure login keychain is added to the list before running tests
- Exit iOS build script if Xcode build failed
> [DX-3624] test: ios build script

- .github/workflows/publish-passport-tutorials.yml
- sample/Assets/Scripts/Passport/_tutorials~/SetCallTimeout/tutorial.md
Updated the tutorial to invoke automation to docs repo
> chore: updated the tutorial to invoke automation to docs repo

- sample/Assets/Scenes/Passport/AuthenticatedScene.unity
- sample/Assets/Scenes/Passport/ZkEvm/ZkEvmGetBalance.unity
- sample/Assets/Scenes/Passport/ZkEvm/ZkEvmGetTransactionReceipt.unity
- sample/Assets/Scenes/Passport/ZkEvm/ZkEvmSendTransaction.unity
- sample/Assets/Scenes/Passport/ZkEvm/ZkEvmSignTypedData.unity
- sample/Assets/Scripts/Passport/PassportInitialisation/PassportInitialisationScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmConnect/ZkEvmConnectScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmGetBalance/ZkEvmGetBalanceScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmGetTransactionReceipt/ZkEvmGetTransactionReceiptScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmRequestAccounts/ZkEvmRequestAccountsScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmSendTransaction/ZkEvmSendTransactionScript.cs
- sample/Assets/Scripts/Passport/ZkEvm/ZkEvmSignTypedData/ZkEvmSignTypedDataScript.cs
Cleaned up zkEVM sample app scripts and scenes by removing unused GameObjects, resolving nullable references, inconsistent field names and standardising debug output messages.
> refactor: sample app zkevm scripts and scenes
