- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scenes/UnauthenticatedScene.unity
- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/WebBrowserClient.cs
* Sometimes, Windows takes longer to start up the browser engine, so adding the ability to set the engine startup time during initialisation.
* Added docs
* Updated screen resolution for sample app on phones
> feat: startup engine timeout

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
When trying to do a silent login, if user does not have network they should not be logged out.
> fix: user is not logged out if there is no network

- src/Packages/Passport/Runtime/Assets/ImmutableAndroid.androidlib/build.gradle
- src/Packages/Passport/Runtime/Assets/ImmutableAndroid.androidlib/proguard-immutable.txt
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
Fixes the `ImmutableAndroid` class being discarded when performing a minified release/build.
> feat: add proguard rules for releases

- src/Packages/Passport/Editor/PassportPostprocess.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/iOS/WebView.mm
- src/Packages/Passport/Runtime/ThirdParty/ImmutableBrowserCore/IWebBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/ImmutableBrowserCore/OnUnityPostMessage.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/WebBrowserClient.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Core/BrowserCommunicationsManagerTests.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
This is the standard way of dealing with SSO on iOS.
Asynchronous error handling is now being bubbled up to PassportImpl
where it can be parsed by their identifier to complete unfinished
tasks.
> feat: use ASWebAuthenticationSession for iOS PKCE

- README.md
- sample/Assets/Scenes/AuthenticatedScene.unity
- sample/Assets/Scripts/AuthenticatedScript.cs
* Update README to include zkEVM functions
* Update sample app labels and fields
> docs: update readme for zkevm functions and update sample app labels

- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebView.bundle.meta
This allows devs to make use of the play scene button. Note, however, that PKCE is not supported in this mode due to deeplinking not being supported in the play mode.
> feat: add support to macOS editor play scene

- sample/Packages/manifest.json
- sample/Packages/packages-lock.json
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Editor/EngineManagement/EngineManagerPostprocess.cs
Previously, Unity complained about Unity Web Browser code if you tried to build an Android app on Windows Editor. So, fixed Windows compilation flags so you can only target the Windows platform on a Windows Editor. 
This change makes more sense, as building and testing a Windows game on a Windows machine is more manageable. If the developer wants to create a Windows game on a Mac machine, they could edit our SDK compilation flag.
Note. I will create another PR that updates the docs to show what platform developers can target using Windows/macOS Editor.
> fix: windows compilation flags

- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Assets/ImmutableAndroid.androidlib/src/main/java/com/immutable/unity/ImmutableAndroid.java
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
* Removed unused `PKCEResult` from the `Passport` class
* Added Android Chrome Custom Tabs callback so the game knows if the user has closed the embedded browser before authenticating.
* Added cancelled check to sample app
> feat: add chrome custom tabs callback to android pkce flow

- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/UnsignedTransferRequest.cs
Amount for ETH transfer was mistakenly done in int, which doesn't support long values for Wei. It has since been replaced for a string and added some description to clarify the expected amount is in Wei.
> fix: amount field to string in ETH

- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
The path to the index file for the macOS editor needs to be corrected. Currently, it’s assuming the path of the sample app, but the location on the SDK could be anywhere on the disk.
> fix: macos editor path to index file

- sample/ProjectSettings/ProjectSettings.asset
Removed macOS URL scheme as we don't require it.
For macOS, we implemented [ASWebAuthenticationSession](https://github.com/immutable/unity-immutable-sdk/blob/698c5189e2bd4c0263bbdb3fff377686bf55a5dc/Plugins/Mac/Sources/WebView.mm#L334) using the `redirectUri` that is passed in from `Passport.Init`. This differs from iOS, which [uses the bundle identifier](https://github.com/immutable/unity-immutable-sdk/blob/698c5189e2bd4c0263bbdb3fff377686bf55a5dc/src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/iOS/WebView.mm#L352) and therefore needs the `redirectUri` scheme to be set for deeplinking to work properly.
> [DX-2503] chore: remove sample app macos url scheme

- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
* On macOS and iOS, plus signs in the JSON response are converted into spaces
> [DX-2502] fix: ios and macos converting plus signs in json response to spaces

- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Model/BrowserResponse.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers.meta
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/JsonHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/JsonHelpers.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/UriHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/UriHelpers.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Core/BrowserCommunicationsManagerTests.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Helpers.meta
- src/Packages/Passport/Tests/Runtime/Scripts/Helpers/UriHelpersTests.cs
- src/Packages/Passport/Tests/Runtime/Scripts/Helpers/UriHelpersTests.cs.meta
* Removed the need for HttpUtility to get query parameters
* Refactored JSON helper to Helper directory
* Simplified sample app client ID as logout redirect URI depends on what we set in the Passport config not in the Hub
> [DX-2524] feat: simplify httputility

- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
* Developers calling `Login` followed by `ConnectImx` should not trigger the device code auth flow twice. Updated `ConnectImx` to stored credentials if they exist before initiating device code auth.
* Updated sample app authenticated scene connect button to use `ConnectImx()` instead of `ConnectImx(useCachedSession: true)`
> [DX-2505] feat: connect imx use saved credentials if they exist so device flow is not triggered again

- .github/pr-labeler/config.yml
- .github/workflows/label-pr.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
* Set up release workflow when a tag is pushed
* Label closed and merged PRs so release Github Action can build a change log
* Link CHANGELOG file to releases
* Remove change log section from README as it is now automated
> ci: set up release github action

- src/Packages/Passport/Editor/PassportPostprocess.cs
- Fixed the `PassportPostprocess` script to try a second `buildDataPath` if the first one does not exist for iOS
> fix: passport post process ios build data path

- .github/workflows/branch-name.yml
Set up a GitHub Action to check pull request branch names so that the correct labels can be applied upon merge.
> ci: check branch name

- .gitignore
- src/Packages/Passport/Runtime/Assets/ImmutableAndroid.androidlib/src/main/java/com/immutable/unity/ImmutableActivity.java
If the user is logged into the browser and uses `LoginPKCE` / `ConnectImxPKCE`, Chrome Custom Tabs will immediately redirect them back to the game. However, there are instances when the Custom Tabs dismiss callback is called before the redirect, rendering the PKCE `CompletionSource` null. This means that the PKCE result cannot be returned to the game.
To prevent this issue, I have added some delay before calling `onCustomTabsDismissed`.
N/A
> [DX-2600] fix: custom tabs dismiss callback triggered before redirect

- src/Packages/Passport/CHANGELOG.md
- src/Packages/Passport/Documentation~/DOCUMENTATION.md
Add the Documentation and Changelog files to the Passport package, so if developers add the package from the Git URL, these files are also included.
N/A
> [DX-2618] docs: add documentation and changelog to passport package

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
Sometimes, the `LoginPKCE`/`ConnectImxPKCE` function might get triggered twice in the integrating game. As a result, the second call can result in an error due to the absence of `pkceCompletionSource` to return a result, as the first call has already nullified it. 
Added a flag to check if the user is currently logged in and only call `TrySetPKCEResult` if the user is in the correct state:
* Call `TrySetPKCEResult` for login if the user is not currently logged in
* Call `TrySetPKCEResult` for logout if the user is currently
N/A
> [DX-2624] feat: set pkce result if user is in the correct state

- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
The index file cannot be loaded by the Gree browser if there are spaces in the path.
Raised by https://github.com/immutable/unity-immutable-sdk/issues/159.
It is now possible for developers to use names with spaces in the titles of their macOS, Android, and iOS applications.
> [DX-2623] fix: gree browser does not load index file if path has spaces

- .github/workflows/stale-issues.yml
Automate adding labels and closing stale issues with Github Actions.
N/A
> [DX-2634] ci: set up stale github action for issues

- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
On certain iOS devices, if an app name contains a space, the SDK fails to locate the index.html file. The change was reverted, only escaping the file path for macOS standalone targets.
Only some iOS devices will be impacted by this.
> [DX-2641] fix: ios file path

- sample/Assets/Scripts/AuthenticatedScript.cs
- sample/Assets/Scripts/UnauthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
In the past, setting the build target to Android or iOS on the Mac Unity Editor would prevent the Unity SDK from running because the web view was not supported. With this update, the SDK now uses the macOS WebView instead if the target is Android or iOS and the Unity Editor is on Mac.
Customers can save development time by targeting Android or iOS and running the SDK on the Mac Unity Editor. However, it's important to note that native Android and iOS WebViews cannot run in the editor, so the macOS WebView is used instead. Therefore, we highly recommend testing the game on an actual device or emulator to ensure it functions properly.
> [DX-2665] feat: ability to target android/ios and run the sdk in the unity mac editor

- sample/Assets/Plugins/Android/proguard-user.txt
- sample/Assets/Plugins/Android/proguard-user.txt.meta
- sample/Assets/Scripts/UnauthenticatedScript.cs
- sample/ProjectSettings/ProjectSettings.asset
As pointed out by https://github.com/immutable/unity-immutable-sdk/issues/172, the `LoginPKCE` and `ConnectImxPKCE` functions do not work on Android if Minify is enabled. This PR added an example demonstrating how to configure Proguard with Minify enabled in the sample game.
Also, fixed the sample application to log out using the appropriate method if the login or connection attempt fails.
If you enable Minify in your game, please follow the instructions in our documentation [here](https://docs.immutable.com/docs/x/sdks/unity/#proguard).
> [DX-2700] fix: android login and connect pkce not working if minify is enabled in sample app

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
The SDK's current logout function performs a local logout and also opens the browser to log them out of the browser session. However, some customers might find the browser popup undesirable. To address this issue, a change has been made to allow users to skip logging out of the browser step and only perform a local logout:
* To skip the Auth0 logout and only perform a local logout, set `hardLogout` to `false` when calling `Logout()` or `LogoutPKCE()`.
* To perform local and Auth0 logout, set the `hardLogout` parameter to `true` when calling the `Logout()` or `LogoutPKCE()` function. This is the default.
Customers can now choose not to display the browser pop-up when logging out. However, if they choose this option, they will remain logged into Passport in the browser until the browser …
> [DX-2713] feat: ability to skip logging out of auth0 in the browser

- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Plugins/VoltstroStudios.UnityWebBrowser.Shared.dll
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/EngineProcess.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/EngineProcess.cs.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/Process.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/Process/IProcess.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/Process/IProcess.cs.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/Process/WindowProcess.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/Engines/Process/WindowProcess.cs.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/WebBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/WebBrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/VoltstroStudios.UnityWebBrowser.asmdef
- Added Voltstros' fixes to attempt to resolve the Windows UnityWebBrowser engine start-up timeout issue. For more details, see https://github.com/Voltstro-Studios/UnityWebBrowser/issues/166.
- Increased Windows UnityWebBrowser engine startup timeout.
When starting the SDK, some Windows users may experience the engine start-up timeout issue. Added Volstros' fixes to attempt to resolve the timeout issue.
> [DX-2753] fix: add voltstro unity web browser fixes for engine timeout

- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Communication/TCPCommunicationLayer.cs
Voltro's UnityWebBrowser now looks for available ports when setting up the TCP communication layer.
Allows customers to run Windows-based games both within the editor and as a game build simultaneously."
> [DX-2771] feat: check for available ports when setting up uwb tcp

- src/Packages/Passport/Runtime/Scripts/Private/Event/AnalyticsEvent.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
Fix nullability errors that show up in older Unity versions.
Customers using older Unity versions can now integrate the SDK without encountering nullability errors.
> [DX-2793] fix: nullables not working for unity 2019

- README.md
- src/Packages/Passport/README.md
Update the contribution section of the Readme to inform people about how to contribute to this repository.
No breaking changes. No production impact. No testing required.
Readme's contribution section
> chore: improve the contribution guide section in readme

- sample/Assets/Scripts/AuthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Response/TransactionReceiptResponse.cs
- Updated the `TransactionReceiptResonse` `status` docs to show all possible values.
- Fixed how the sample app checks the status of a transaction.
When calling `ZkEvmGetTransactionReceipt`, customers can now easily understand each transaction status.
> [DX-2784] docs: transaction receipt response status field docs, sample app transaction status check

- sample/Assets/Scripts/AuthenticatedScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Response/TransactionReceiptResponse.cs
- Updated docs for `TransactionReceiptResponse` status
- Removed unnecessary code in sample app
Updated documentation for `TransactionReceiptResponse` `status` field.
> [DX-2834] docs: update transaction receipt response docs, remove unnecessary code in sample app

- .github/scripts/check_team_membership.sh
- .github/workflows/linter.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .github/workflows/update-version.yml
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/SdkVersionInfoHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/SdkVersionInfoHelpers.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/VersionInfo.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
[DX-2896](https://immutable.atlassian.net/browse/DX-2896)
Will not impact customers.
- Track Unity SDK version
[DX-2896]: https://immutable.atlassian.net/browse/DX-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [DX-2896] Track Unity SDK version

- .github/scripts/check_team_membership.sh
- .github/workflows/update-version.yml
Fix the SDK membership script in the update version workflow. Only SDK team members can run the workflow now.
No customer impact.
> fix: update version workflow

- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
Ensures that the provided `timeoutMs` for Device Code Authentication is valid.
Ensures that the timeout parameter for both `Login` and `ConnectImx` is valid.
> [DX-3001] feat: device code auth timeout value check

- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Nullify Passport Instance upon application exit on Windows.
> [DX-3019] feat: nullify passport on quit

- .github/workflows/release.yml
The [Create Release](https://github.com/immutable/unity-immutable-sdk/actions/workflows/release.yml) workflow was previously triggered after the [Tag Release](https://github.com/immutable/unity-immutable-sdk/actions/workflows/tag.yml) workflow completes, regardless of whether all steps in the Tag Release workflow succeeded.
This PR updates the Create Release workflow only to run if the Tag Release workflow completes with a success status. This ensures that the release process only proceeds when the tagging process is successful.
> [DX-2981] ci: fix release workflow

- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/chrome_elf.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/d3dcompiler_47.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libEGL.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libGLESv2.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libcef.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/vk_swiftshader.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/vulkan-1.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Plugins/VoltstroStudios.UnityWebBrowser.Shared.dll.meta
Fix compilation errors when opening the project on MacOS.
- `Singleton` class inside `Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs` won't collide with class of the same name in user project on MacOS.
- DLLs inside `Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/` won't load on MacOS
- Correctly configure a few other DLLs.
> Fix compilation errors on MacOS

- src/Packages/Passport/Runtime/ThirdParty/ImmutableBrowserCore/GameBridge.cs
Fixed game bridge path for iOS.
Fixed the issue where the SDK could not load the game bridge file when running in the Unity Editor and targeting iOS.
> fix: game bridge path for ios device

- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Support disabling [domain reloading](https://docs.unity3d.com/Manual/DomainReloading.html).
Use the SDK with Domain Reloading disabled.
> [DX-3076] feat: support domain reloading

- sample/Assets/Scripts/SelectAuthMethodScript.cs
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging.meta
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/Immutable.Passport.Core.Logging.asmdef
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/Immutable.Passport.Core.Logging.asmdef.meta
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/LogLevel.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/LogLevel.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/PassportLogger.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Logging/PassportLogger.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/JsonHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/UriHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Immutable.Passport.Runtime.Private.asmdef
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Immutable.Passport.Runtime.asmdef
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/GreeBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Communication/TCPCommunicationLayer.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Core/WebBrowserClient.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Logging/DefaultUnityWebBrowserLogger.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/VoltstroStudios.UnityWebBrowser.asmdef
- src/Packages/Passport/Tests/Runtime/Scripts/PassportTests.cs
Added support for configuring log levels, allowing finer control over the verbosity of log messages in the SDK.
> [DX-3051] feat: add logging level

- sample/Assets/Scripts/SelectAuthMethodScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/InitRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
Allow `logoutRedirectUri` to be set even when `redirectUri` is not set.
Previously, logging out using the Device Code Auth flow redirected users to a localhost page. With this PR, users can now set a `logoutRedirectUri` without needing to configure the `redirectUri` (typically used in the PKCE flow), allowing them to choose the page they are redirected to after a successful logout.
> [DX-3221] feat: allow logout redirect uri to be set for device code auth

- .github/workflows/update-version.yml
Modify "Update Version" workflow to automatically increment the version number based on the upgrade type (major, minor, or patch level), rather than requiring a specific version string.
N/A
> [DX-3288] ci: update version based on upgrade type

- .github/workflows/update-version.yml
- src/Packages/Marketplace/Immutable.Marketplace.asmdef
- src/Packages/Marketplace/Immutable.Marketplace.asmdef.meta
- src/Packages/Marketplace/OnRamp.meta
- src/Packages/Marketplace/OnRamp/OnRamp.cs
- src/Packages/Marketplace/OnRamp/OnRamp.cs.meta
- src/Packages/Marketplace/package.json
- src/Packages/Marketplace/package.json.meta
- add marketplace package
- add onramp method to get the link
> [sdk-3286] add marketplace package to support transak link

- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Update Passport class docs for logout redirect URI and return type for login.
> [DX-3324] docs: update passport docs

- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/Runtime/Communication/TCPCommunicationLayer.cs
Change Voltstro UnityWebBrowser TCP timeouts to max allowed based on how Voltstro fixed [this](https://github.com/Voltstro-Studios/UnityWebBrowser/issues/300) issue.
With increased Voltstro UnityWebBrowser TCP timeouts, customers should not see errors like `System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.`.
> [DX-3348] fix: tcp timeout

- sample/Assets/Plugins/Android/AndroidManifest.xml
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scenes
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts
- src/Packages/Passport/package.json
* Fixed sample app deeplinks
* Add sample scenes and scripts to Passport packages using symbolic links.
* Update Passport package description
> [DX-3362] feat: samples

- .github/workflows/test-build.yml
- .github/workflows/ui-tests.yml
- sample/Assets/Editor/MacBuilder.cs
- sample/Tests/requirements.txt
- sample/Tests/test.py
Start adding UI Tests to CI
- build StandaloneOSX for AltTester
- a hello world python test
> [SDK-3347] add ui tests to CICD (WIP)

- .github/workflows/test-build.yml
- .github/workflows/ui-tests.yml
- sample/Assets/Editor/AndroidBuilder.cs
- sample/Assets/Editor/WindowsBuilder.cs
- sample/Tests/src/device_code_login_windows.py
- sample/Tests/switch-app.ps1
- sample/Tests/test_mac.sh
- sample/Tests/test_windows.ps1
Add Windows build and UI tests on CI
> [SDK-3403] add Windows UI tests

- src/Packages/ZkEvmApi/package.json
Bumped up zkEVM API package to Alpha v0.2.0, as NFT metadata endpoints have been updated. This is manual until we move to a stable/non-alpha version.
> [DX-3426] chore: update zkevm api package version

- sample/Assets/Editor/MobileBuilder.cs
- sample/Assets/Scenes/SelectAuthMethod.unity
- sample/ProjectSettings/ProjectSettings.asset
- Added ability to set AltTester host for mobile builder
- Set stripping level of sample app to minimal for UI tests
> [DX-3432] test: ability to specify host for mobile builder

- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/chrome_elf.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/d3dcompiler_47.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libEGL.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libGLESv2.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/libcef.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/vk_swiftshader.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser.Engine.Cef.Win-x64/Engine/vulkan-1.dll.meta
This PR fixes an issue where `.dll` files are duplicated in the Windows build output, appearing both in `XXX_Data/ImmutableSDK/Runtime/UWB` and `XXX_Data/Plugins/x86_64`.
Removes duplicated `.dll` files from the Windows build, reducing build size and avoiding potential conflicts.
> [DX-3450] fix: windows build duplicate dlls

- .github/workflows/ui-tests.yml
- sample/Tests/browserstack.android.yml
- sample/Tests/browserstack.ios.yml
- sample/Tests/src/fetch_otp.py
- sample/Tests/test/test_ios.py
> [SDX-3448] iOS browserstack tests on CICD

- .github/workflows/ui-tests.yml
- sample/Assets/Editor/MobileBuilder.cs
- sample/Tests/browserstack.ios.yml
- sample/Tests/src/fetch_otp.py
- sample/Tests/test/test.py
- sample/Tests/test/test_ios.py
- sample/build_ios.sh
- Set up GitHub Action to build iOS for UI tests
- Updated MobileBuilder script to take in optional bundle identifier for iOS. This is only for UI tests.
> [DX-3448] test: ios ui test set up

- sample/Tests/test/test.py
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/dev.voltstro.unitywebbrowser@2.2.5/Plugins/VoltstroStudios.UnityWebBrowser.Shared.dll.meta
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/org.nuget.voltrpc@3.2.1/VoltRpc.dll.meta
- Made sure UnityWebBrowser dlls are only for Editor and Standalone platforms
- Uncomment register off-chain test case
> [DX-3465] fix: uwb dll platforms

- .github/workflows/diff.yml
- src/Packages/Marketplace/README.md
- src/Packages/Passport/README.md
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/InitRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- Updated the README for Passport and Marketplace packages
- Removed unused imports
- Simplified nullable values, marked private fields/arguments as nullable
- Only call get logout URL if `hardLogout` is true
- Don't compare the Passport package README with the Unity SDK README to ensure consistency, as we now have multiple packages.
> refactor: remove unused imports, nullables, update readmes

- sample/Assets/Editor/MacBuilder.cs
- sample/Assets/Editor/MobileBuilder.cs
- sample/Assets/Editor/WindowsBuilder.cs
- sample/Packages/manifest.json
- sample/Packages/packages-lock.json
- sample/Tests/test/test_android.py
- Added Android UI tests for Passport, IMX, zkEVM and other non-auth related functions
- Updated AltTester version
> [DX-3412] test: android ui tests for passport, imx and zkevm functions

- sample/Tests/test/test.py
- sample/Tests/test/test_android.py
Added Android UI tests for PKCE relogin, reconnect, connect and logout.
> [DX-3414] test: android ui tests for pkce relogin, reconnect, connect and logout

- src/Packages/Marketplace/Runtime/Bridge.meta
- src/Packages/Marketplace/Runtime/Bridge/Bridge.cs
- src/Packages/Marketplace/Runtime/Bridge/Bridge.cs.meta
- src/Packages/Marketplace/Runtime/Swap/Swap.cs
- Added function to generate the bridge URL into the Marketplace package
- Make swap URL parameters optional
- Customers can utilise the Marketplace package to generate the bridge URL for use in their game.
> [DX-3527] feat: function to generate bridge URL

- src/Packages/Marketplace/Runtime/Bridge/Bridge.cs
Make bridge URL parameters optional.
> [DX-3527] feat: make bridge url params optional

- src/Packages/Marketplace/Runtime/Bridge/Bridge.cs
At times, the bridge URL doesn't set the from/to tokens correctly. Changing them to lowercase resolves the issue.
> [DX-3540] feat: make bridge url fromToken and toToken query params lowercase

- sample/Tests/test/test_ios.py
iOS UI tests for Passport, IMX, zkEVM and other functions.
> [DX-3536] test: ui tests for ios passport, imx, zkevm and other functions

- sample/Assets/Scenes/SelectAuthMethod.unity
- src/Packages/Marketplace/Runtime/OnRamp/OnRamp.cs
- src/Packages/Marketplace/Runtime/Swap/Swap.cs
- src/Packages/Marketplace/Samples~/SampleScenesScripts/Scenes/AuthenticatedScene.unity
- Removed the hardcoded Swap API key as developers need to get the key from Immutable Hub.
- Refactored on-ramp params
- Fixed sample app select auth method scene missing font
- Updated sample app text
> [DX-3548] feat: swap api key

- src/Packages/Marketplace/Runtime/LinkConfig.cs
Renamed `env` to `environment` in `LinkConfig`.
> [DX-3550] refactor: rename env to environment in link config

- sample/Assets/Scripts/Marketplace/BridgeScript.cs
- sample/Assets/Scripts/Marketplace/OnRampScript.cs
- sample/Assets/Scripts/Marketplace/SwapScript.cs
- src/Packages/Marketplace/Runtime/LinkFactory.cs
- src/Packages/Marketplace/Runtime/LinkQueryParams.cs
- src/Packages/Marketplace/Runtime/LinkQueryParams.cs.meta
* Refactored the marketplace link generation functions to utilise structs for query parameters.
* Alphabetised the on-ramp query parameters dictionary.
* Added an additional argument `extraQueryParams` to `GenerateOnRampLink` so that developers can include more configurations. Developers can refer to the Transak documentation for further configuration fields.
> [DX-3550] refactor: marketplace query params

- src/Packages/Marketplace/Runtime/LinkQueryParams.cs
Update Marketplace package docs for default values.
> docs: update marketplace docs

- sample/Tests/test/test_mac.py
Sometimes, if the UI tests have previously failed and the test is triggered again, it may not work because the sample app could be in an incorrect state. Added steps to reset the app to the correct state so the UI tests can run again.
> [DX-3567] test: reset mac app state

- .github/workflows/update-version.yml
This PR updates the GitHub Actions workflow to include a new "Mark as alpha release" checkbox. When selected, the updated version will have the `.alpha` suffix unless it already exists.
- Added a `mark_as_alpha` input (boolean checkbox).  
- Adjusted version bumping logic:  
- If **not marked as alpha**, `.alpha` is removed if present.  
- If **marked as alpha**, `.alpha` is added if not already present.  
- Ensured correct version increments for both **patch** and **minor** updates. 
Example:
| Current Version | Upgrade Type | Mark as Alpha | New Version |  
|----------------|-------------|---------------|-------------|  
| 1.3.0.alpha   | Patch       | No            | 1.3.0       |  
| 1.3.0.alpha   | Minor       | No            | 1.4.0       |  
| 1.3.0         | Patch       | No …
> [DX-3571] ci: update version gh action to handle alpha releases

- sample/Tests/test/test.py
- sample/Tests/test/test_windows.py
- Sometimes, if the UI tests have previously failed and the test is triggered again, it may not work because the sample app could be in an incorrect state. Added steps to reset the app to the correct state so the UI tests can run again.
- Print test output for improved debugging.
- Introduce delays between each send transaction call as sometimes the nonce hasn't updated yet.
> [DX-3572] test: reset windows sample app if in the wrong state

- .github/workflows/ui-tests.yml
- sample/Tests/test/test.py
- Our SDK needs access to the keychain to retrieve stored tokens. This means that when UI tests are executed, a prompt for the login password appears, which, so far, needs to be entered manually to continue the tests. This PR is to create and use a temporary keychain instead.
- Avoid printing access and ID tokens in tests, even if they're obfuscated by GitHub.
> [DX-3575] test: fix mac ui requiring keychain access

- sample/Tests/test/test.py
- sample/Tests/test/test_ios.py
Added iOS UI tests for PKCE relogin, reconnect, connect and logout.
> [DX-3537] test: ios ui tests for pkce relogin, reconnect, connect and logout

- sample/Packages/packages-lock.json
- sample/ProjectSettings/ProjectSettings.asset
- src/Packages/Passport/Runtime/ThirdParty/ImmutableBrowserCore/GameBridge.cs
Resolved game bridge file issue where it wouldn’t load if the project path contained spaces.
> [DX-3581] fix: game bridge file cannot be loaded with path has a space

- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
Resolved UwbWebView instantiation issue as reported by #412.
Customers should no longer receive the warning error regarding UwbWebView when using the SDK on Windows.
> [DX-3585] fix: uwb view instantiation

- sample/Assets/Editor/MacBuilder.cs
- sample/Assets/Editor/MobileBuilder.cs
- sample/Assets/Editor/WindowsBuilder.cs
- sample/Assets/Scripts/Passport/AuthenticatedScript.cs
- sample/Assets/Scripts/Passport/SelectAuthMethodScript.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/dev.voltstro.unitywebbrowser@2.2.5/Runtime/UwbWebView.cs
- Updated deprecated functions
- Fixed nullable fields
- Fixed Windows warnings
> [DX-3621] fix: windows warnings

- .github/workflows/ui-tests.yml
Disable Mobile UI tests until we upgrade our BrowserStack license.
> [DX-3630] ci: disable out mobile ui tests

- .github/workflows/release.yml
Currently, when a user downloads the Passport ZIP archive from the Releases page and installs the SDK locally on a Mac, they may encounter a Gatekeeper warning about the .bundle file. This happens because the .bundle inside the ZIP is unsigned, which leads macOS to flag it and block execution.
However, when the SDK is installed via Git (e.g., using a Git URL), the files are not quarantined, and no such warning appears.
This PR removes the Passport ZIP archive from the Releases page, as installing via Git provides a smoother and more reliable experience.
> [DX-3657] chore: no passport zip archive in releases

- sample/Assets/Scenes/Passport/SelectAuthMethod.unity
- sample/Assets/Scripts/Passport/AuthenticatedScript.cs
- sample/Assets/Scripts/Passport/SampleAppManager.cs
- sample/Assets/Scripts/Passport/SelectAuthMethodScript.cs
- sample/Assets/Scripts/Passport/UnauthenticatedScript.cs
- sample/Tests/test/test_windows.py
- src/Packages/Passport/Private.meta
- src/Packages/Passport/Private/Helpers.meta
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/AuthenticatedScript.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/SampleAppManager.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/SelectAuthMethodScript.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/UnauthenticatedScript.cs
Added **alpha support for PKCE on Windows**. Enables system browser launch and redirect handling via custom URI schemes.
Enables PKCE login flow on Windows.  
Note: This is an **alpha release**. It requires PowerShell, which is pre-installed on Windows 10/11. On older versions of Windows, PowerShell may need to be installed manually.
This feature requires PowerShell to function. While PowerShell is pre-installed on Windows 10/11, manual installation may be needed on older Windows versions.
> [DX-3682] feat: windows pkce (alpha)

- sample/Assets/Editor/WindowsBuilder.cs
- sample/Tests/test/test.py
- sample/Tests/test/test_windows.py
- sample/Tests/test/test_windows_helpers.py
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs
Added UI Testing to **alpha support for PKCE on Windows**.
> [ID-3594] UI Testing to **alpha support for PKCE on Windows**.

- sample/Assets/Scenes/Passport/SelectAuthMethod.unity
- sample/Assets/Scripts/Passport/PassportInitialisation/PassportInitialisationScript.cs
- sample/Assets/Scripts/Passport/_tutorials~/PassportInitialisation/tutorial.md
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scenes/Passport/SelectAuthMethod.unity
- src/Packages/Passport/Samples~/SamplesScenesScripts/Scripts/Passport/SelectAuthMethodScript.cs
- Fixed command prompt errors when printing logs during PKCE authentication on Windows  
- During browser redirection on Windows, the open prompt will display the correct app name without the `.cmd` extension  
- Corrected documentation related to PKCE  
- PKCE flow on Windows now logs cleanly without printing errors to the command prompt window  
- Updated Windows default protocol name to use the application name  
- Improved documentation makes PKCE setup and usage clearer
> [ID-3737] fix: windows pkce cmd errors, protocol name, pkce docs

- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/dev.voltstro.unitywebbrowser@2.2.5/Runtime/Logging/DefaultUnityWebBrowserLogger.cs
- src/Packages/Passport/Runtime/ThirdParty/UnityWebBrowser/dev.voltstro.unitywebbrowser@2.2.5/Runtime/UwbWebView.cs
Fixed an issue where the Windows WebView did not respect the log level configured in Passport when running in the Unity Editor, as reported in #513.
Log filtering now works correctly in the Windows Unity Editor.
> [ID-3839] fix: uwb log level

- sample/Assets/Scenes/Passport/UnauthenticatedScene.unity
- sample/Assets/Scripts/Passport/Login/LoginScript.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/DirectLoginMethod.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/DirectLoginMethod.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/GetPKCEAuthUrlRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/GetPKCEAuthUrlRequest.cs.meta
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
- Add direct login methods (Google, Apple, Facebook) leveraged from Game Bridge. This allow users to skip the standard login page to redirect directly to their preferred authenticated provider
[ID-3819](https://immutable.atlassian.net/browse/ID-3819)
[ID-3819]: https://immutable.atlassian.net/browse/ID-3819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add direct login support (#3819)

- src/Packages/Passport/Runtime/Scripts/Private/Core/BrowserCommunicationsManager.cs
- src/Packages/Passport/Runtime/Scripts/Private/Core/Model/BrowserRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/Event/AnalyticsEvent.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/JsonHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/UriHelpers.cs
- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs
- src/Packages/Passport/Runtime/Scripts/Private/Model/Request/UnsignedTransferRequest.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportFunction.cs
- src/Packages/Passport/Runtime/Scripts/Private/PassportImpl.cs
Fixes the write location for Windows deeplink-related files when the game is installed into Program Files, avoiding the need for elevated permissions. Also fixes some compiler warnings.
[ID-3851](https://immutable.atlassian.net/browse/ID-3851)
Fixed Windows deeplink file write location for installs in Program Files, and resolved compiler warnings.
[ID-3851]: https://immutable.atlassian.net/browse/ID-3851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ID-3851] fix: windows deeplink write location, warnings

- src/Packages/Passport/Runtime/Scripts/Public/Passport.cs
[ID-3873](https://immutable.atlassian.net/browse/ID-3873)
Adds validation for Windows platforms to ensure redirect URIs use custom protocols (e.g. `mygame://callback`) instead of `http`/`https`.
[ID-3873]: https://immutable.atlassian.net/browse/ID-3873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: windows custom protocols for redirects

- src/Packages/Passport/Runtime/Scripts/Private/Helpers/WindowsDeepLink.cs
Fix login crash in Windows IL2CPP builds. By replacing unsupported `Process.MainModule` API with IL2CPP-compatible `Environment.GetCommandLineArgs()`
Jira: [ID-3951](https://immutable.atlassian.net/browse/ID-3951)
This fix resolves login failures that prevent the SDK from working in Windows Standalone IL2CPP builds. Customers can now successfully use the login functionality in production Windows IL2CPP builds without crashing.
- Fixed IL2CPP crash during login caused by unsupported `Process.MainModule` API
[ID-3951]: https://immutable.atlassian.net/browse/ID-3951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login failures on window il2cpp builds

- .github/workflows/test-build.yml
- .github/workflows/ui-tests.yml
Comment out the unnecessary mobile build in the UI test action, as it is already handled by the test build action. It is kept commented in case mobile UI tests are reintroduced in the future.
> ci: remove unnecessary mobile build in ui test action
